# -*- coding: utf-8 -*-
"""Data Exploration Pandas - College Majors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8wlyTo-HzLtk4VgzEvs09b_9ZwHSbNT
"""

import pandas

df = pandas.read_csv('salaries_by_college_major.csv')
df.head()

df.shape

df.columns

df.isna()

df.tail()

cleaned_df = df.dropna()
cleaned_df.tail()

cleaned_df['Starting Median Salary']

cleaned_df['Starting Median Salary'].idxmax()

cleaned_df['Undergraduate Major'].loc[43]

cleaned_df.loc[43]

# Difference between earnings of 10th and 90th percentile
spread_col = cleaned_df['Mid-Career 90th Percentile Salary'] - cleaned_df['Mid-Career 10th Percentile Salary']
cleaned_df.insert(1, 'Spread', spread_col)
cleaned_df.head()

# Sorting by lowest spread
low_risk = cleaned_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

# Grouping data
cleaned_df.groupby('Group').count()

pandas.options.display.float_format = '{:,.2f}'.format
cleaned_df.groupby('Group').mean()

